### ISSUE TITLE
Question: Yaml Events or use of `yaml/events`

### ISSUE THREAD

**Issue by aymanosman** [esilkensen/yaml#46]
Quick question.

I'm interested in customizing the data-structures produced by the parser. For example, I want to create an ordered mapping object instead of using `#hash()` structures or perhaps use immutable hashes.

Would you suggest I use the `yaml/events` module? If so, I could try that out and maybe document it.

Thanks for your work.

**Comment by esilkensen** [comment]
Hey @aymanosman, thanks for your question! Sorry I am just seeing it now.

So the parser produces events, which the "composer" turns into scalar/sequence/mapping nodes, which the "constructor" turns nodes into Racket values.

Maybe nodes is the level you want instead of events?

### Custom constructors 

One way to hook into the library is writing custom constructors -- for example, to override the "tag:yaml.org,2002:map" tag and turn all mappings into immutable hashes:

```racket
(define (construct-immutable-mapping node)
  (define mapping (construct-mapping node))
  (make-immutable-hash (hash->list mapping)))

(define immutable-mapping-constructor
  (yaml-constructor hash? "tag:yaml.org,2002:map" construct-immutable-mapping))
```

The `yaml-constructors` parameter controls custom constructors:

```racket
> (immutable? (string->yaml "{ Clark: Evans, Brian: Ingerson, Oren: Ben-Kiki }"))
#f
> (parameterize ([yaml-constructors (list immutable-mapping-constructor)])
    (immutable? (string->yaml "{ Clark: Evans, Brian: Ingerson, Oren: Ben-Kiki }"))) 
#t
```

That said, I could imagine adding additional keyword arguments to the `read-yaml`, etc. functions for things like: "return all mappings as immutable hashes instead of mutable"

### Builtin constructors

The library defines a couple of Racket-specific tags and constructors:
https://github.com/esilkensen/yaml/blob/9fe9fc170b5208b98e8ee559cc0001f904ed8004/yaml/constructor.rkt#L480-L483

PR's would certainly be welcome to add support for additional Racket types.

**Comment by aymanosman** [comment]
Thanks Erik. The `composer` level turned out to be the best fit for my use-case (I needed to preserve the order that the mapping keys were encountered, I just returned a list of pairs). 

Using the `yaml-constructors` parameter didn't work because I'm not returning a `yaml?` anymore.

**Comment by esilkensen** [comment]
Cool, sounds good!

I wonder if you uncovered a potential bug? The yaml-constructors parameter should extend the yaml? contract to accept new types returned by custom constructors — but for that matter, lists of pairs should already be considered yaml — if you have control over the input, tagging those mappings with “!!omap” should get them to parse as ordered maps and come back as ordered lists of pairs in Racket.

Anyway, happy to hear you are on your way - if you have an example around of what wasn’t working though, I will check it out!

**Comment by aymanosman** [comment]
> I wonder if you uncovered a potential bug? The yaml-constructors parameter should extend the yaml? contract to accept new types returned by custom constructors

You are right, but how do you 'extend' contracts?

> but for that matter, lists of pairs should already be considered yaml

Also correct, I misspoke. I only noticed the contract violation when I was returning the `mapping-node` directly (for debugging purposes).

> if you have control over the input, tagging those mappings with “!!omap” should get them to parse as ordered maps and come back as ordered lists of pairs in Racket.

I don't have control over the input. My actually use case is: take a yaml file representing the configuration to a particular service (in this case, it was concourse https://concourse-ci.org/). Read it in, transform it and write it back out. My intention was to preseve the order of the mapping entries so as to 'minimally' affect the file being transformed.

It turned out that the 'node' level was adequate for my needs (although a little unwieldy).

**Comment by esilkensen** [comment]
Got it, makes sense, thanks @aymanosman! 

>You are right, but how do you 'extend' contracts?

By that I only mean the `yaml?` function loops over the `yaml-constructors` and `yaml-representers` parameter values to dynamically include any custom `type?` predicates.
